version: "3"
services:
  level2tocql:
    image: ejtrader/level2_to_cql:rust
    container_name: level2_to_cql
    environment:
      APP_MODE: 'tick'  # full / book / tick
      API_ADDRESS: ${API_ADDRESS} # ip_or_domain:port 127.0.0.3:4444
      SECRET_KEY: ${SECRET_KEY}
      PUBLIC_KEY: ${PUBLIC_KEY}
      CASSANDRA_HOST: ${CASSANDRA_HOST} # 127.0.0.5 for not default port add 127.0.0.5:port
      CASSANDRA_USERNAME: ${CASSANDRA_USERNAME}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
     
      KEYSPACE: ${KEYSPACE}
      TOPIC: ${TOPIC}
    volumes:
      - level2tocql:/app
      

volumes:
  level2tocql: {}
